// import { marked } from "./marked"; // Assumed to be a local module
// import { unescape } from "./unescape"; // Assumed to be a local module

// export { markdownToRequests };

// /**
//  * Converts Markdown text to an array of Google Docs API requests.
//  *
//  * This function takes Markdown text and a starting index, and uses the 'marked'
//  * library to parse the Markdown into tokens.  It then converts these tokens
//  * into an array of Google Docs API requests suitable for use with the
//  * `batchUpdate` method.
//  *
//  * @param {string} markdown - The Markdown text to convert.
//  * @param {number} startIndex - The starting index in the Google Doc for the inserted content.
//  * @returns {Array<object>} An array of Google Docs API requests.
//  */
// function markdownToRequests(markdown, startIndex) {
//   const tokens = marked.lexer(markdown); // Parse the Markdown text into tokens.
//   return tokensToRequests(tokens, startIndex); // Convert the tokens to API requests.
// }

// /**
//  * Converts an array of Markdown tokens into an array of Google Docs API requests.
//  *
//  * This function iterates over the Markdown tokens and generates the corresponding
//  * Google Docs API requests to insert and format the content.  It handles various
//  * Markdown elements, including paragraphs, spaces, code blocks, headings, blockquotes,
//  * and lists.
//  *
//  * @param {Array<object>} tokens - An array of Markdown tokens generated by the 'marked' library.
//  * @param {number} startIndex - The starting index in the Google Doc for the inserted content.
//  * @returns {Array<object>} An array of Google Docs API requests.
//  */
// function tokensToRequests(tokens, startIndex) {
//   let current = startIndex; // Keep track of the current insertion index.
//   // console.log("TOKENS", tokens, startIndex); // For debugging

//   // Process each Markdown token and generate the appropriate API requests.
//   return tokens.flatMap((token) => {
//     switch (token.type) {
//       case "paragraph":
//         return insertFormattedText(token, "NORMAL_TEXT"); // Handle paragraphs.
//       case "space":
//         return insertSpace(token); // Handle spaces.
//       case "code":
//         return insertFormattedText(token, "NORMAL_TEXT"); // Handle code blocks (treated as normal text).
//       case "heading":
//         return insertFormattedText(token, `HEADING_${token.depth}`); // Handle headings.
//       case "blockquote":
//         return insertFormattedText(token, "NORMAL_TEXT"); // Handle blockquotes.
//       case "list":
//         return insertList(token.items, token.ordered, 0); // Handle lists.
//       default:
//         return []; // Ignore unknown token types.
//     }
//   });

//   /**
//    * Inserts formatted text into the Google Doc.
//    *
//    * This function handles the insertion of text with associated formatting, such as
//    * bold, italic, or links.  It uses the TextStyles class to parse the token's text
//    * and extract any formatting information.  It then generates the necessary
//    * Google Docs API requests to insert the text and apply the formatting.
//    *
//    * @param {object} token - The Markdown token representing the text to insert.
//    * @param {string} namedStyleType - The named style type to apply to the text (e.g., "NORMAL_TEXT", "HEADING_1").
//    * @returns {Array<object>} An array of Google Docs API requests.
//    */
//   function insertFormattedText(token, namedStyleType) {
//     const { requests, text: withoutBreak } = new TextStyles(
//       current,
//       token
//     ).parse(); // Parse the text and extract styles.
//     const text = `${withoutBreak}\\n`; // Add a newline character.

//     // Apply the named style type if provided.
//     if (namedStyleType) {
//       requests.unshift({
//         updateParagraphStyle: {
//           range: range(text.length), // Define the range of text to style.
//           paragraphStyle: { namedStyleType }, // Set the named style type.
//           fields: "namedStyleType", // Specify the field to update.
//         },
//       });
//     }

//     // Insert the text.
//     requests.unshift({ insertText: { text, location: location() } });

//     current += text.length; // Update the current insertion index.
//     return requests; // Return the generated requests.
//   }

//   /**
//    * Inserts a space into the Google Doc.
//    *
//    * This function handles the insertion of spaces, including newline characters.
//    *
//    * @param {object} token - The Markdown token representing the space to insert.
//    * @returns {Array<object>} An array of Google Docs API requests.
//    */
//   function insertSpace(token) {
//     const text = token.raw.startsWith("\n") ? token.raw.slice(1) : token.raw; // Get the raw text, removing leading newline.
//     const result = [
//       {
//         insertText: { text, location: location() }, // Insert the space.
//       },
//     ];
//     return advance(result, text.length); // Update the current index and return.
//   }

//   /**
//    * Creates a range object for a given length.
//    *
//    * This is a helper function to simplify the creation of range objects used in
//    * the Google Docs API requests.
//    *
//    * @param {number} length - The length of the range.
//    * @returns {object} A range object with 'startIndex' and 'endIndex' properties.
//    */
//   function range(length) {
//     return { startIndex: current, endIndex: current + length };
//   }

//   /**
//    * Creates a location object for the current insertion index.
//    *
//    * This is a helper function to simplify the creation of location objects used in
//    * the Google Docs API requests.
//    *
//    * @returns {object} A location object with an 'index' property.
//    */
//   function location() {
//     return { index: current };
//   }

//   /**
//    * Inserts a list into the Google Doc.
//    *
//    * This function handles the insertion of both ordered and unordered lists.  It
//    * recursively processes list items and their sub-lists, generating the necessary
//    * Google Docs API requests to insert the list items and apply the appropriate
//    * formatting.
//    *
//    * @param {Array<object>} items - An array of Markdown tokens representing the list items.
//    * @param {boolean} ordered - A boolean indicating whether the list is ordered.
//    * @param {number} depth - The nesting depth of the list.
//    * @returns {Array<object>} An array of Google Docs API requests.
//    */
//   function insertList(items, ordered, depth) {
//     const start = current;
//     // This is necessary to counteract a gnarly side-effect of creating a
//     // bullet list: the indent markers are being removed during that change,
//     // and change all of the ranges. So we have to make sure that the next
//     // request accounts for that.
//     let depthToRemove = 0;
//     const list = descendIntoList(items, ordered, depth).flat(); // Recursively process list items.

//     // Create the paragraph bullets for the entire list range.
//     list.push({
//       createParagraphBullets: {
//         range: { startIndex: start, endIndex: current },
//         bulletPreset: ordered
//           ? "NUMBERED_DECIMAL" // Use decimal numbers for ordered lists.
//           : "BULLET_DISC_CIRCLE_SQUARE", // Use disc, circle, and square for unordered lists.
//       },
//     });

//     current -= depthToRemove; // Adjust current index after list processing.
//     return list;

//     /**
//      * Recursively processes list items and their sub-lists.
//      *
//      * This helper function handles the recursive processing of list items and their
//      * sub-lists.  It generates the API requests to insert the text of each list
//      * item and recursively calls itself to process any nested lists.
//      *
//      * @param {Array<object>} items - An array of Markdown tokens representing the list items.
//      * @param {boolean} ordered - A boolean indicating whether the list is ordered.
//      * @param {number} depth - The nesting depth of the list.
//      * @returns {Array<object>} An array of Google Docs API requests.
//      */
//     function descendIntoList(items, ordered, depth) {
//       const list = items.flatMap((item) => {
//         // For item, item.type === "list_item".
//         const indent = "\t".repeat(depth); // Generate indentation string.
//         depthToRemove += depth; // Track depth for index adjustment.
//         const result = [];
//         const subList = item.tokens?.find((token) => token.type === "list"); // Find any sub-list.

//         if (subList) {
//           // If there's a sub-list, process the item's text and then the sub-list.
//           result.push(insertItemText(indent, item.tokens.at(0))); // Insert item text.
//           result.push(...descendIntoList(subList.items, ordered, depth + 1)); // Recurse for sub-list.
//         } else {
//           // If no sub-list, just insert the item's text.
//           result.push(insertItemText(indent, item.tokens.at(0)));
//         }
//         return result;
//       });
//       return list;
//     }

//     /**
//      * Inserts the text of a list item with indentation.
//      *
//      * This helper function generates the API requests to insert the text of a
//      * list item, including the appropriate indentation.
//      *
//      * @param {string} indent - The indentation string for the list item.
//      * @param {object} token - The Markdown token representing the list item's text.
//      * @returns {Array<object>} An array of Google Docs API requests.
//      */
//     function insertItemText(indent, token) {
//       const offset = current + indent.length; // Calculate the offset for the text.
//       const { requests, text: withoutIndent } = new TextStyles(
//         offset,
//         token
//       ).parse(); // Parse the text and extract styles.
//       const text = `${indent}${withoutIndent}\n`; // Add indent and newline.

//       // Apply normal text style and insert the text.
//       requests.unshift({
//         updateParagraphStyle: {
//           range: range(text.length),
//           paragraphStyle: { namedStyleType: "NORMAL_TEXT" },
//           fields: "namedStyleType",
//         },
//       });
//       requests.unshift({ insertText: { text, location: location() } });

//       current += text.length; // Update the current index.
//       return requests;
//     }
//   }

//   /**
//    * Advances the current insertion index.
//    *
//    * This helper function updates the current insertion index by a given length
//    * and returns the provided result.
//    *
//    * @param {Array<object>} result - The result to return.
//    * @param {number} length - The length to advance the index by.
//    * @returns {Array<object>} The provided result.
//    */
//   function advance(result, length) {
//     current += length;
//     return result;
//   }
// }

// /**
//  * A class for parsing text styles from Markdown tokens.
//  *
//  * This class is used to extract text styles (e.g., bold, italic, links) from Markdown
//  * tokens and generate the corresponding Google Docs API requests to apply those
//  * styles.
//  */
// class TextStyles {
//   #offset; // The starting offset for the text.
//   #tokens; // The Markdown tokens to parse.
//   #styles = []; // The array of style requests.

//   /**
//    * Constructs a new TextStyles instance.
//    *
//    * @param {number} offset - The starting offset for the text.
//    * @param {object} token - The Markdown token containing the text and styles.
//    */
//   constructor(offset, token) {
//     this.#offset = offset;
//     this.#tokens = token.tokens || []; // Use an empty array if no tokens.
//   }

//   /**
//    * Creates a range object for a given start index and length.
//    *
//    * @param {number} startIndex - The starting index of the range.
//    * @param {number} length - The length of the range.
//    * @returns {object} A range object with 'startIndex' and 'endIndex' properties.
//    */
//   range(startIndex, length) {
//     return { startIndex, endIndex: startIndex + length };
//   }

//   /**
//    * Adds a text style request.
//    *
//    * This method adds a Google Docs API request to apply a specific text style
//    * (e.g., bold, italic, link) to a given range of text.
//    *
//    * @param {number} startIndex - The starting index of the text to style.
//    * @param {number} length - The length of the text to style.
//    * @param {object} textStyle - An object containing the text style properties (e.g., { bold: true }, { link: { url: '...' } }).
//    */
//   style(startIndex, length, textStyle) {
//     this.#styles.push({
//       updateTextStyle: {
//         range: this.range(startIndex, length), // Define the range of text to style.
//         textStyle, // The text style to apply.
//         fields: Object.keys(textStyle).join(","), // Specify the fields to update.
//       },
//     });
//   }

//   /**
//    * Parses the Markdown tokens and extracts text styles.
//    *
//    * This method iterates over the Markdown tokens, extracts the text and any
//    * associated styles, and generates the corresponding Google Docs API requests
//    * to apply those styles.
//    *
//    * @returns {object} An object containing the array of style requests and the plain text.
//    */
//   parse() {
//     let current = this.#offset; // The current insertion index.
//     let text = ""; // The plain text being extracted.

//     // Process each token and extract text/styles.
//     for (let token of this.#tokens) {
//       const length = token.text.length;
//       text += unescape(token.text); // Add the unescaped text.

//       // Apply styles based on the token type.
//       switch (token.type) {
//         case "strong":
//           this.style(current, length, { bold: true }); // Apply bold style.
//           break;
//         case "em":
//           this.style(current, length, { italic: true }); // Apply italic style.
//           break;
//         case "codespan":
//           this.style(current, length, {
//             weightedFontFamily: {
//               fontFamily: "Fira Code", // Apply a monospaced font for code spans.
//             },
//           });
//           break;
//         case "del":
//           this.style(current, length, { strikethrough: true }); // Apply strikethrough style.
//           break;
//         case "link":
//           this.style(current, length, { link: { url: token.href } }); // Apply link style.
//           break;
//         case "escape":
//           console.log("ESCAPE", token); // Log escape tokens (for debugging).
//           break;
//         // Add other cases as needed (e.g., for images, inline code, etc.).
//       }
//       current += length; // Update the current index.
//     }

//     return {
//       requests: this.#styles, // Return the style requests.
//       text, // And the plain text.
//     };
//   }
// }
